---
title: "WEEK_7_PRACT"
output: pdf_document
date: "2024-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# LIBRARIES
library(here)
library(janitor)
library(sf)
library(tidyverse)
library(tmap)
library(sf)
library(spdep) # calculate Moran’s I and any similar statistics


```

```{r}
install.packages("spdep")
```

```{r}
# LOADING DATA


LondonWards <- st_read(here::here("statistical-gis-boundaries-london",
                                  "ESRI", "London_Ward.shp"))

LondonWardsMerged <- st_read(here::here( "statistical-gis-boundaries-london", "ESRI", "London_Ward_CityMerged.shp")) %>%
  
  st_transform(.,27700)

```


```{r}
# CLEANING AND SELECTING NEEDED COLUMNS
 WardData <- read_csv("https://data.london.gov.uk/download/ward-profiles-and-atlas/772d2d64-e8c6-46cb-86f9-e52b4c7851bc/ward-profiles-excel-version.csv", locale = locale(encoding = "latin1"),
                      na = c("NA", "n/a")) %>%
  clean_names()

LondonWardsMerged <- LondonWardsMerged %>%
  left_join(WardData,
            by = c("GSS_CODE" = "new_code"))%>%
dplyr::distinct(GSS_CODE, .keep_all = T)%>%
dplyr::select(GSS_CODE, ward_name, average_gcse_capped_point_scores_2014)
  
  
```

```{r}
#have a look to check that it's 
#in the right projection
st_crs(LondonWardsMerged)


```

```{r}
BluePlaques <- st_read(here::here("open-plaques-london-2018-04-08.geojson")) %>%
    st_transform(.,27700)


```

```{r}
tmap_mode("plot")
tm_shape(LondonWardsMerged) + tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(BluePlaques) + tm_dots(col = "blue")


```

```{r}
summary(BluePlaques)
```

```{r}
BluePlaquesSub <- BluePlaques[LondonWardsMerged,]

tm_shape(LondonWardsMerged) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```

```{r}
# DATA MANIPULATION
example <- st_intersects(LondonWardsMerged, BluePlaquesSub)

example
```

```{r}
check_example <- LondonWardsMerged %>%#
  st_join(BluePlaquesSub)%>%
  filter(ward_name == "Kingston upon Thames - Coombe Hill")

```

```{r}
points_sf_joined <- LondonWardsMerged %>%
  mutate(n = lengths(st_intersects(., BluePlaquesSub))) %>%
  janitor::clean_names() %>%
  
#calculating area
  mutate(area = st_area(.))  %>%

#calculating density per ward
  mutate(density = n/area) %>%
  
#select density and some other variables
  dplyr::select(density, ward_name, gss_code, n, average_gcse_capped_point_scores_2014)
  
  
```

```{r}
points_sf_joined <- points_sf_joined %>%
  group_by(gss_code)%>%
  summarise(density = first(density),
            wardname = first(ward_name),
            plaquecount = first(n))

tm_shape(points_sf_joined) + 
  tm_polygons("density", 
     style = "jenks",
     palette = "PuOr",
     midpoint = NA,
     popup.vars = c("wardname", "density"),
     title = "Blue Plaque Density")
```

```{r}
#First calculate the centroids of all Wards in London

coordsW <- points_sf_joined %>%
  st_centroid() %>%
  st_geometry()

plot(coordsW, axes = TRUE)

```

```{r}
#create a neighbours list
LWard_nb <- points_sf_joined %>%
  poly2nb(., queen=T)

summary(LWard_nb)

```


```{r}
#plot them
plot(LWard_nb, st_geometry(coordsW), col="red")
#add a map underneath
plot(points_sf_joined$geometry, add=T)
```

```{r}
# creating a spatial weights matrix from these weights
LWard_lw <- LWard_nb %>%
  nb2mat(., style = "B")

sum(LWard_lw)

```

```{r}
sum(LWard_lw[1,])
```
```{r}
Lward.lw <- LWard_nb %>%
  nb2listw(., style="C")
```

##Moran's I

```{r}
# Moran's I
I_LWard_Global_Density <- points_sf_joined %>%
  pull(density) %>%
  as.vector() %>%
  moran.test(., Lward.lw)

I_LWard_Global_Density
  
```


##Geary's C 
This tells us whether similar values or dissimilar values are clustering

```{r}
C_LWard_Global_Density <- points_sf_joined %>%
   pull(density) %>%
  as.vector() %>%
  geary.test(., Lward.lw)
  
C_LWard_Global_Density 
```














